# Generated by Django 5.0.3 on 2024-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
